all: touchdemo

CFLAGS	= -Wall -g -O2 -Wno-unused-variable
LDFLAGS	= -lm -lrt -lpthread 

touchdemo : Font.h Graphics.h Touch.h touchdemo.c
		$(CC) $(CFLAGS) -o touchdemo touchdemo.c $(LDFLAGS) 
clean:
	rm -f  *.o




