all: xy

CFLAGS	= -Wall -g -O2 -Wno-unused-variable
LDFLAGS	= -lm -lrt -lpthread  -lwiringPi

mcp3002 : mcp3002.h mcp3002.c xy.c
		$(CC) $(CFLAGS) -o xy mcp3002.c xy.c $(LDFLAGS) 
clean:
	rm -f  *.o

install:
	cp xy ../../bin/




